# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: grafana-pvc
#   namespace: {{ .Release.Namespace }}  
# spec:
#   storageClassName: "yc-network-hdd"
#   accessModes:
#     - ReadWriteOnce 
#   resources:
#     requests:
#       storage: 2Gi
#   volumeName: grafana-pv