{
 "title": "momo-store",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Response_timing_ms_bucket (quatile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_timing_ms_bucket{handler=\"/categories/\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response_timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(response_timing_ms_sum [5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of dumblings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(dumplings_listing_count[$__rate_interval])",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}