apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  labels:
    name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
  - hosts:
    - www.momostore.ru
    - www.momostore.online
    secretName: app-tls
  rules:
  - host: www.momostore.ru   
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "momo-store.fullname" . }}-svc
            port: 
              number: 80
      - pathType: Prefix
        path: "/auth/whoami"
        backend:
          service:
            name: {{ .Release.Name }}-backend-svc
            port: 
              number: 8081
      - pathType: Prefix
        path: "/products"
        backend:
          service:
            name: {{ .Release.Name }}-backend-svc
            port: 
              number: 8081
      - pathType: Prefix
        path: "/categories"
        backend:
          service:
            name: {{ .Release.Name }}-backend-svc
            port: 
              number: 8081             
  - host: www.momostore.online  
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "momo-store.fullname" . }}-svc
            port: 
              number: 80
      - pathType: Prefix
        path: "/auth/whoami"
        backend:
          service:
            name: {{ .Release.Name }}-backend-svc
            port: 
              number: 8081
      - pathType: Prefix
        path: "/products"
        backend:
          service:
            name: {{ .Release.Name }}-backend-svc
            port: 
              number: 8081
      - pathType: Prefix
        path: "/categories"
        backend:
          service:
            name: {{ .Release.Name }}-backend-svc
            port: 
              number: 8081
  - host: grafana.momostore.ru
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: grafana
            port: 
              number: 3000  