# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: sla-manager-service-role
#   namespace: default
#   labels:
#     app: sla-manager-app
# rules:
# - apiGroups: ["monitoring.coreos.com"] # "" indicates the core API group
#   resources: ["prometheusrules"]
#   verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: role-binding
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: sla-manager-service-role
# subjects:
# - kind: ServiceAccount
#   name: default
#   namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fabric8-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io