groups:
- name: Momo-store-rules
  rules:
  
  #all instances
  - alert: InstanceDown
    expr: up == 0
    for: 0m
    labels:
      severity: 'critical'
    annotations:
      summary: Instance {{ $labels.instance }} down
      description: "{{ $labels.kubernetes_pod_name }} of job {{ $labels.job }} has been down for more than 1m"  

  # for exmp.
  - alert: KubernetesPodNotHealthy
    expr: kube_pod_status_phase{phase=~"Pending|Unknown|Failed"} > 0
    for: 1h
    labels:
      severity: 'critical'
    annotations:
      summary: Kubernetes Pod not healthy (instance {{ $labels.instance }})
      description: "Pod has been in a non-ready state for longer than an hour.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  # # Request latency > 100ms.
  # - alert: HighRequestLatency
  #   expr: >
  #         histogram_quantile(0.95,  
  #         sum(rate(http_server_requests_seconds_bucket{status!~"4..",uri="/api/orders"}[5m])) by (le)) > 0.01
  #   for: 1m
  #   labels:
  #     severity: 'warning'
  #   annotations:
  #     summary: "Successful requests"
  #     description: "Successful requests within 5m with a latency > 100ms"

  # #error 500
  # - alert: Errors 500
  #   expr: rate(http_server_requests_seconds_count{status="500"}[1m]) > 0
  #   for: 0m
  #   labels:
  #     severity: 'warning'
  #   annotations:
  #     summary: "Error 500"
  #     description: "Error 500 > 0"

  # #any error
  # - alert: Any error code
  #   expr: >
  #         sum(increase(http_server_requests_seconds_count{status=~"400|526",uri="/actuator/prometheus"}[2m])) > 0
  #   for: 0m
  #   labels:
  #     severity: 'warning'
  #   annotations:
  #     summary: "Any error"
  #     description: "{{ $value }} errors to /actuator/prometheus within 2m"